# Generated by Django 5.2 on 2026-04-12 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=15, verbose_name='status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='orders.order', verbose_name='order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL, verbose_name='raised by')),
            ],
            options={
                'verbose_name': 'dispute',
                'verbose_name_plural': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
