# Generated by Django 5.2 on 2026-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bold', models.CharField(default='Get In', max_length=100, verbose_name='Title (bold part)')),
                ('title_italic', models.CharField(default='Know', max_length=100, verbose_name='Title (italic part)')),
                ('image', models.ImageField(blank=True, help_text='Displayed on the left of the Get In Know section.', null=True, upload_to='about/top/', verbose_name='Top image')),
                ('description', models.TextField(default='Welcome to RapidVenta, where digital innovation meets auction excellence. Discover exclusive items and bid your way to great deals.', verbose_name='Description')),
                ('feature_1', models.CharField(blank=True, default='Ready to boost your bidding strategy', max_length=200, verbose_name='Feature 1')),
                ('feature_2', models.CharField(blank=True, default='Join our exclusive auction community', max_length=200, verbose_name='Feature 2')),
                ('feature_3', models.CharField(blank=True, default='Verified sellers, real products, fair prices', max_length=200, verbose_name='Feature 3')),
                ('feature_4', models.CharField(blank=True, default='Live countdowns — bid until the last second', max_length=200, verbose_name='Feature 4')),
                ('feature_5', models.CharField(blank=True, default='Secure payments and buyer protection', max_length=200, verbose_name='Feature 5')),
                ('stat_auctions_label', models.CharField(default='Auctions', max_length=50, verbose_name='Auctions label')),
                ('stat_auctions_sub', models.CharField(default='Live Right Now', max_length=50, verbose_name='Auctions sub-label')),
                ('stat_categories_label', models.CharField(default='Categories', max_length=50, verbose_name='Categories label')),
                ('stat_categories_sub', models.CharField(default='To Browse', max_length=50, verbose_name='Categories sub-label')),
                ('stat_sellers_label', models.CharField(default='Sellers', max_length=50, verbose_name='Sellers label')),
                ('stat_sellers_sub', models.CharField(default='Verified Sellers', max_length=50, verbose_name='Sellers sub-label')),
                ('cta_text', models.CharField(default='Start Bidding Now', max_length=100, verbose_name='CTA button text')),
                ('testimonial_text', models.TextField(blank=True, default='RapidVenta transformed how I buy and sell collectibles. The platform is transparent, fast, and the support team is always available.', verbose_name='Testimonial quote')),
                ('testimonial_author', models.CharField(blank=True, default='A Happy Buyer', max_length=100, verbose_name='Testimonial author')),
                ('bottom_image', models.ImageField(blank=True, help_text='Displayed on the right of the testimonial row.', null=True, upload_to='about/bottom/', verbose_name='Bottom image')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
