# Generated by Django 5.2 on 2026-04-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_about_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bold', models.CharField(default="How It's", max_length=100, verbose_name='Title (bold part)')),
                ('title_italic', models.CharField(default='Work', max_length=100, verbose_name='Title (italic part)')),
                ('subtitle', models.CharField(default='Start bidding in 4 simple steps and win exclusive auction items', max_length=255, verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'How It Works Section',
                'verbose_name_plural': 'How It Works Section',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('icon', models.CharField(default='bi-star-fill', help_text='E.g. bi-person-plus-fill — find icons at https://icons.getbootstrap.com', max_length=100, verbose_name='Bootstrap icon class')),
                ('title', models.CharField(max_length=100, verbose_name='Step title')),
                ('item_1', models.CharField(blank=True, max_length=200, verbose_name='Sub-item 1')),
                ('item_2', models.CharField(blank=True, max_length=200, verbose_name='Sub-item 2')),
                ('item_3', models.CharField(blank=True, max_length=200, verbose_name='Sub-item 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.howitworkssection')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order'],
            },
        ),
    ]
