# Generated by Django 5.2 on 2026-04-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_process_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bold', models.CharField(default='Frequently Asked', max_length=100, verbose_name='Title (bold part)')),
                ('title_italic', models.CharField(default='Questions', max_length=100, verbose_name='Title (italic part)')),
                ('subtitle', models.CharField(default='Everything you need to know about bidding on RapidVenta', max_length=255, verbose_name='Subtitle')),
                ('contact_heading', models.CharField(default='Ask the help community — write to us now!', max_length=200, verbose_name='Contact card heading')),
                ('contact_label', models.CharField(default='To Send Mail', max_length=100, verbose_name="Contact label (e.g. 'To Send Mail')")),
                ('contact_email', models.EmailField(default='info@rapidventa.com', help_text='Questions submitted via the form are sent to this address.', max_length=254, verbose_name='Contact / recipient email')),
                ('form_heading', models.CharField(default='Any Question?', max_length=100, verbose_name='Form heading')),
                ('form_btn_text', models.CharField(default='Send Now', max_length=50, verbose_name='Submit button text')),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.faqsection')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order'],
            },
        ),
    ]
