# Generated by Django 5.2 on 2026-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='The fast, transparent online auction house. Bid smart, win big.', max_length=255, verbose_name='Tagline')),
                ('whatsapp_url', models.CharField(blank=True, default='https://wa.me/+584122392711', max_length=200, verbose_name='WhatsApp URL')),
                ('facebook_url', models.URLField(blank=True, default='#', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='#', verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, default='#', verbose_name='Twitter / X URL')),
                ('step_1', models.CharField(default='Register & get validated', max_length=200, verbose_name='Step 1')),
                ('step_2', models.CharField(default='Browse live auctions', max_length=200, verbose_name='Step 2')),
                ('step_3', models.CharField(default='Place your highest bid', max_length=200, verbose_name='Step 3')),
                ('step_4', models.CharField(default='Win & complete the order', max_length=200, verbose_name='Step 4')),
                ('copyright_name', models.CharField(default='RapidVenta', max_length=100, verbose_name='Company name (copyright)')),
                ('bottom_text', models.CharField(blank=True, default='Built with love using Django 5.2', max_length=255, verbose_name='Bottom tagline')),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
    ]
