# Generated by Django 5.2 on 2026-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopbarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@rapidventa.com', max_length=254, verbose_name='Contact email')),
                ('support_url', models.CharField(default='https://wa.me/+584122392711', help_text="Full URL for the 'Customer support' link (e.g. WhatsApp, tel:, mailto:)", max_length=200, verbose_name='Support link URL')),
                ('support_label', models.CharField(default='Customer support', max_length=100, verbose_name='Support link label')),
                ('btn_how_to_bid', models.CharField(default='HOW TO BID', max_length=80, verbose_name="'How to Bid' button label")),
                ('btn_sell', models.CharField(default='SELL YOUR ITEM', max_length=80, verbose_name="'Sell' button label")),
                ('language_label', models.CharField(default='Language', max_length=50, verbose_name='Language label')),
            ],
            options={
                'verbose_name': 'Topbar Section',
                'verbose_name_plural': 'Topbar Section',
            },
        ),
    ]
