# Generated by Django 5.2 on 2026-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_topbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbarsection',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended: transparent PNG, ~180 × 50 px. Leave blank to use the default static logo.', null=True, upload_to='site/logo/', verbose_name='Site logo'),
        ),
        migrations.AddField(
            model_name='topbarsection',
            name='nav_auctions',
            field=models.CharField(default='Auctions Category', max_length=60, verbose_name="'Auctions Category' link label"),
        ),
        migrations.AddField(
            model_name='topbarsection',
            name='nav_contact',
            field=models.CharField(default='Contact', max_length=60, verbose_name="'Contact' link label"),
        ),
        migrations.AddField(
            model_name='topbarsection',
            name='nav_home',
            field=models.CharField(default='Home', max_length=60, verbose_name="'Home' link label"),
        ),
        migrations.AddField(
            model_name='topbarsection',
            name='search_placeholder',
            field=models.CharField(default='Search your product...', max_length=100, verbose_name='Search box placeholder'),
        ),
        migrations.AddField(
            model_name='topbarsection',
            name='site_name',
            field=models.CharField(default='RapidVenta', help_text='Used in image alt text and browser title.', max_length=100, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='topbarsection',
            name='support_url',
            field=models.CharField(default='https://wa.me/+584122392711', help_text='Full URL for the support link (WhatsApp, tel:, mailto:, …)', max_length=200, verbose_name='Support link URL'),
        ),
    ]
