# Generated by Django 5.2 on 2026-04-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_topbar_navbar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='logo',
            field=models.ImageField(blank=True, help_text='Leave blank to use the same logo as the navbar.', null=True, upload_to='site/footer_logo/', verbose_name='Footer logo'),
        ),
    ]
