# Generated by Django 5.2 on 2026-04-10 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('min_public_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='minimum public price')),
                ('max_public_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='maximum public price')),
                ('secret_reserve_price', models.DecimalField(decimal_places=2, help_text='Auction is VOID if highest bid falls below this.', max_digits=12, verbose_name='secret reserve price')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed – Sold'), ('VOID', 'Void – Reserve Not Met'), ('REPUBLISHED', 'Republished')], db_index=True, default='DRAFT', max_length=15, verbose_name='status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category', verbose_name='category')),
                ('original_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='republications', to='listings.listing', verbose_name='original listing')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
