# Generated by Django 5.2 on 2026-04-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Buyers can skip the auction and purchase immediately at this price.', max_digits=12, null=True, verbose_name='buy now price'),
        ),
    ]
