# Generated by Django 5.2 on 2026-04-10 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='bid amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='placed at')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='listings.listing', verbose_name='listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='bidder')),
            ],
            options={
                'verbose_name': 'bid',
                'verbose_name_plural': 'bids',
                'ordering': ['-amount'],
                'unique_together': {('user', 'listing', 'amount')},
            },
        ),
    ]
